### ISSUE TITLE
boat not getting injured (or not enough?) when question time runs out

### ISSUE THREAD

**Issue by janisfuh** [jshuaf/Aquaforces#32] opened 2016-07-19 03:52 UTC

**Comment by alexandernext** [comment] 2016-07-19 03:58
Duplicate of #27

**Comment by jshuaf** [comment] 2016-07-19 14:28
the boat is not supposed to get injured when the time runs out.

**Comment by jshuaf** [comment] 2016-07-19 14:28
feature, not bug

**Comment by janisfuh** [comment] 2016-07-20 06:55
dude no

**Closed as completed** 2016-07-22 00:12 UTC
Labels: bug
